// Code generated by goctl. DO NOT EDIT!
// Source: sabeagent.proto

package sabeagent

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SabeAgent interface {
		SabeReply(ctx context.Context, in *SabeReplyRequest, opts ...grpc.CallOption) (*SabeReplyResponse, error)
	}

	defaultSabeAgent struct {
		cli zrpc.Client
	}
)

func NewSabeAgent(cli zrpc.Client) SabeAgent {
	return &defaultSabeAgent{
		cli: cli,
	}
}

func (m *defaultSabeAgent) SabeReply(ctx context.Context, in *SabeReplyRequest, opts ...grpc.CallOption) (*SabeReplyResponse, error) {
	client := NewSabeAgentClient(m.cli.Conn())
	return client.SabeReply(ctx, in, opts...)
}
