// Code generated by goctl. DO NOT EDIT!
// Source: sabeagent.proto

package server

import (
	"context"

	"github.com/moyrne/sabe-reply/sabeagent/internal/logic"
	"github.com/moyrne/sabe-reply/sabeagent/internal/svc"
	"github.com/moyrne/sabe-reply/sabeagent/sabeagent"
)

type SabeAgentServer struct {
	svcCtx *svc.ServiceContext
	sabeagent.UnimplementedSabeAgentServer
}

func NewSabeAgentServer(svcCtx *svc.ServiceContext) *SabeAgentServer {
	return &SabeAgentServer{
		svcCtx: svcCtx,
	}
}

func (s *SabeAgentServer) SabeReply(ctx context.Context, in *sabeagent.SabeReplyRequest) (*sabeagent.SabeReplyResponse, error) {
	l := logic.NewSabeReplyLogic(ctx, s.svcCtx)
	return l.SabeReply(in)
}
