// Code generated by goctl. DO NOT EDIT.
package types

type SabeReplyRequest struct {
	Kind       string `json:"kind"`
	Sender     string `json:"sender"`
	Receiver   string `json:"receiver"`
	Content    string `json:"content"`
	RawContent string `json:"raw_content"`
}

type SabeReplyResponse struct {
	Reply string `json:"reply"`
}
